# Site settings
title: Ben C. Sclodnick
email: sclodnbc@mcmaster.ca
url: https://bsclod.com
description: "MSc. Psychology, Department of Psychology, Neuroscience & Behaviour at McMaster University"
keywords: "Ben, Ben Sclodnick, Psychology, McMaster, McMaster University, Neuroscience, Memory"
skills: "MSc. Psychology — Memory and Cognition <br /> Department of Psychology, Neuroscience & Behaviour, McMaster University"
meta_author: Sclodnick Ben

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ele4e9; #80B3FF
  primary-rgb: "128, 0, 0" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: <!--Dr. Henry Jekyll--!>
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BenSclod?lang=en
  - title: facebook
    url: https://www.facebook.com/ben.sclodnick
  - title: instagram
    url: https://www.instagram.com/bsclod

# Postal address (add as many lines as necessary)
address:
  - line: Hamilton, ON, Canada

# Credits content
credits: 'credits'

# Build settings
markdown: kramdown
permalink: pretty
